/******************** Copyright wisearm.com *********************************
* File Name         : stm32gpio_def.h
* Author            : Îâ´´Ã÷(aleyn.wu)
* Version           : V1.0.0
* Create Date       : 2009-02-02
* Last Update       : 2017-07-18
* Description       : GPIO Name define.
********************************************************************************/
#ifndef __STM32EXT_GPIO_DEF_H
#define __STM32EXT_GPIO_DEF_H

#if defined (STM32F0)
  #define GPIO_PORT_BASE              (uint32_t)0x0000
  #define GPIO_PORT_A                 GPIO_PORT_SET(0x10)
  #define GPIO_PORT_B                 GPIO_PORT_SET(0x20)
  #define GPIO_PORT_C                 GPIO_PORT_SET(0x30)
  #define GPIO_PORT_D                 GPIO_PORT_SET(0x40)
  #define GPIO_PORT_E                 GPIO_PORT_SET(0x50)
  #define GPIO_PORT_F                 GPIO_PORT_SET(0x60)
  #define GPIO_PORT_G                 GPIO_PORT_SET(0x70)
#elif defined (STM32F1)
  #define GPIO_PORT_BASE              (uint32_t)0x0800
  #define GPIO_PORT_A                 GPIO_PORT_SET(0x10)
  #define GPIO_PORT_B                 GPIO_PORT_SET(0x20)
  #define GPIO_PORT_C                 GPIO_PORT_SET(0x30)
  #define GPIO_PORT_D                 GPIO_PORT_SET(0x40)
  #define GPIO_PORT_E                 GPIO_PORT_SET(0x50)
  #define GPIO_PORT_F                 GPIO_PORT_SET(0x60)
  #define GPIO_PORT_G                 GPIO_PORT_SET(0x70)
#elif defined (STM32F4)
  #define GPIO_PORT_BASE              (uint32_t)0x0000
  #define GPIO_PORT_A                 GPIO_PORT_SET(0x10)
  #define GPIO_PORT_B                 GPIO_PORT_SET(0x20)
  #define GPIO_PORT_C                 GPIO_PORT_SET(0x30)
  #define GPIO_PORT_D                 GPIO_PORT_SET(0x40)
  #define GPIO_PORT_E                 GPIO_PORT_SET(0x50)
  #define GPIO_PORT_F                 GPIO_PORT_SET(0x60)
  #define GPIO_PORT_G                 GPIO_PORT_SET(0x70)
  #define GPIO_PORT_H                 GPIO_PORT_SET(0x80)
  #define GPIO_PORT_I                 GPIO_PORT_SET(0x90)
  #define GPIO_PORT_J                 GPIO_PORT_SET(0xA0)
  #define GPIO_PORT_K                 GPIO_PORT_SET(0xB0)
#endif

#define GPIO_PIN_0                  GPIO_PIN_SET(0)
#define GPIO_PIN_1                  GPIO_PIN_SET(1)
#define GPIO_PIN_2                  GPIO_PIN_SET(2)
#define GPIO_PIN_3                  GPIO_PIN_SET(3)
#define GPIO_PIN_4                  GPIO_PIN_SET(4)
#define GPIO_PIN_5                  GPIO_PIN_SET(5)
#define GPIO_PIN_6                  GPIO_PIN_SET(6)
#define GPIO_PIN_7                  GPIO_PIN_SET(7)
#define GPIO_PIN_8                  GPIO_PIN_SET(8)
#define GPIO_PIN_9                  GPIO_PIN_SET(9)
#define GPIO_PIN_10                 GPIO_PIN_SET(10)
#define GPIO_PIN_11                 GPIO_PIN_SET(11)
#define GPIO_PIN_12                 GPIO_PIN_SET(12)
#define GPIO_PIN_13                 GPIO_PIN_SET(13)
#define GPIO_PIN_14                 GPIO_PIN_SET(14)
#define GPIO_PIN_15                 GPIO_PIN_SET(15)

#define GPIO_NULL                   0
#define GPIO_PA(PIN)                (GPIO_PORT)(GPIO_PORT_A | PIN)
#define GPIO_PA0                    GPIO_PA(GPIO_PIN_0)
#define GPIO_PA1                    GPIO_PA(GPIO_PIN_1)
#define GPIO_PA2                    GPIO_PA(GPIO_PIN_2)
#define GPIO_PA3                    GPIO_PA(GPIO_PIN_3)
#define GPIO_PA4                    GPIO_PA(GPIO_PIN_4)
#define GPIO_PA5                    GPIO_PA(GPIO_PIN_5)
#define GPIO_PA6                    GPIO_PA(GPIO_PIN_6)
#define GPIO_PA7                    GPIO_PA(GPIO_PIN_7)
#define GPIO_PA8                    GPIO_PA(GPIO_PIN_8)
#define GPIO_PA9                    GPIO_PA(GPIO_PIN_9)
#define GPIO_PA10                   GPIO_PA(GPIO_PIN_10)
#define GPIO_PA11                   GPIO_PA(GPIO_PIN_11)
#define GPIO_PA12                   GPIO_PA(GPIO_PIN_12)
#define GPIO_PA13                   GPIO_PA(GPIO_PIN_13)
#define GPIO_PA14                   GPIO_PA(GPIO_PIN_14)
#define GPIO_PA15                   GPIO_PA(GPIO_PIN_15)

#define GPIO_PB(PIN)                (GPIO_PORT)(GPIO_PORT_B | PIN)
#define GPIO_PB0                    GPIO_PB(GPIO_PIN_0)
#define GPIO_PB1                    GPIO_PB(GPIO_PIN_1)
#define GPIO_PB2                    GPIO_PB(GPIO_PIN_2)
#define GPIO_PB3                    GPIO_PB(GPIO_PIN_3)
#define GPIO_PB4                    GPIO_PB(GPIO_PIN_4)
#define GPIO_PB5                    GPIO_PB(GPIO_PIN_5)
#define GPIO_PB6                    GPIO_PB(GPIO_PIN_6)
#define GPIO_PB7                    GPIO_PB(GPIO_PIN_7)
#define GPIO_PB8                    GPIO_PB(GPIO_PIN_8)
#define GPIO_PB9                    GPIO_PB(GPIO_PIN_9)
#define GPIO_PB10                   GPIO_PB(GPIO_PIN_10)
#define GPIO_PB11                   GPIO_PB(GPIO_PIN_11)
#define GPIO_PB12                   GPIO_PB(GPIO_PIN_12)
#define GPIO_PB13                   GPIO_PB(GPIO_PIN_13)
#define GPIO_PB14                   GPIO_PB(GPIO_PIN_14)
#define GPIO_PB15                   GPIO_PB(GPIO_PIN_15)

#define GPIO_PC(PIN)                (GPIO_PORT)(GPIO_PORT_C | PIN)
#define GPIO_PC0                    GPIO_PC(GPIO_PIN_0)
#define GPIO_PC1                    GPIO_PC(GPIO_PIN_1)
#define GPIO_PC2                    GPIO_PC(GPIO_PIN_2)
#define GPIO_PC3                    GPIO_PC(GPIO_PIN_3)
#define GPIO_PC4                    GPIO_PC(GPIO_PIN_4)
#define GPIO_PC5                    GPIO_PC(GPIO_PIN_5)
#define GPIO_PC6                    GPIO_PC(GPIO_PIN_6)
#define GPIO_PC7                    GPIO_PC(GPIO_PIN_7)
#define GPIO_PC8                    GPIO_PC(GPIO_PIN_8)
#define GPIO_PC9                    GPIO_PC(GPIO_PIN_9)
#define GPIO_PC10                   GPIO_PC(GPIO_PIN_10)
#define GPIO_PC11                   GPIO_PC(GPIO_PIN_11)
#define GPIO_PC12                   GPIO_PC(GPIO_PIN_12)
#define GPIO_PC13                   GPIO_PC(GPIO_PIN_13)
#define GPIO_PC14                   GPIO_PC(GPIO_PIN_14)
#define GPIO_PC15                   GPIO_PC(GPIO_PIN_15)

#define GPIO_PD(PIN)                (GPIO_PORT)(GPIO_PORT_D | PIN)
#define GPIO_PD0                    GPIO_PD(GPIO_PIN_0)
#define GPIO_PD1                    GPIO_PD(GPIO_PIN_1)
#define GPIO_PD2                    GPIO_PD(GPIO_PIN_2)
#define GPIO_PD3                    GPIO_PD(GPIO_PIN_3)
#define GPIO_PD4                    GPIO_PD(GPIO_PIN_4)
#define GPIO_PD5                    GPIO_PD(GPIO_PIN_5)
#define GPIO_PD6                    GPIO_PD(GPIO_PIN_6)
#define GPIO_PD7                    GPIO_PD(GPIO_PIN_7)
#define GPIO_PD8                    GPIO_PD(GPIO_PIN_8)
#define GPIO_PD9                    GPIO_PD(GPIO_PIN_9)
#define GPIO_PD10                   GPIO_PD(GPIO_PIN_10)
#define GPIO_PD11                   GPIO_PD(GPIO_PIN_11)
#define GPIO_PD12                   GPIO_PD(GPIO_PIN_12)
#define GPIO_PD13                   GPIO_PD(GPIO_PIN_13)
#define GPIO_PD14                   GPIO_PD(GPIO_PIN_14)
#define GPIO_PD15                   GPIO_PD(GPIO_PIN_15)

#define GPIO_PE(PIN)                (GPIO_PORT)(GPIO_PORT_E | PIN)
#define GPIO_PE0                    GPIO_PE(GPIO_PIN_0)
#define GPIO_PE1                    GPIO_PE(GPIO_PIN_1)
#define GPIO_PE2                    GPIO_PE(GPIO_PIN_2)
#define GPIO_PE3                    GPIO_PE(GPIO_PIN_3)
#define GPIO_PE4                    GPIO_PE(GPIO_PIN_4)
#define GPIO_PE5                    GPIO_PE(GPIO_PIN_5)
#define GPIO_PE6                    GPIO_PE(GPIO_PIN_6)
#define GPIO_PE7                    GPIO_PE(GPIO_PIN_7)
#define GPIO_PE8                    GPIO_PE(GPIO_PIN_8)
#define GPIO_PE9                    GPIO_PE(GPIO_PIN_9)
#define GPIO_PE10                   GPIO_PE(GPIO_PIN_10)
#define GPIO_PE11                   GPIO_PE(GPIO_PIN_11)
#define GPIO_PE12                   GPIO_PE(GPIO_PIN_12)
#define GPIO_PE13                   GPIO_PE(GPIO_PIN_13)
#define GPIO_PE14                   GPIO_PE(GPIO_PIN_14)
#define GPIO_PE15                   GPIO_PE(GPIO_PIN_15)

#define GPIO_PF(PIN)                (GPIO_PORT)(GPIO_PORT_F | PIN)
#define GPIO_PF0                    GPIO_PF(GPIO_PIN_0)
#define GPIO_PF1                    GPIO_PF(GPIO_PIN_1)
#define GPIO_PF2                    GPIO_PF(GPIO_PIN_2)
#define GPIO_PF3                    GPIO_PF(GPIO_PIN_3)
#define GPIO_PF4                    GPIO_PF(GPIO_PIN_4)
#define GPIO_PF5                    GPIO_PF(GPIO_PIN_5)
#define GPIO_PF6                    GPIO_PF(GPIO_PIN_6)
#define GPIO_PF7                    GPIO_PF(GPIO_PIN_7)
#define GPIO_PF8                    GPIO_PF(GPIO_PIN_8)
#define GPIO_PF9                    GPIO_PF(GPIO_PIN_9)
#define GPIO_PF10                   GPIO_PF(GPIO_PIN_10)
#define GPIO_PF11                   GPIO_PF(GPIO_PIN_11)
#define GPIO_PF12                   GPIO_PF(GPIO_PIN_12)
#define GPIO_PF13                   GPIO_PF(GPIO_PIN_13)
#define GPIO_PF14                   GPIO_PF(GPIO_PIN_14)
#define GPIO_PF15                   GPIO_PF(GPIO_PIN_15)

#define GPIO_PG(PIN)                (GPIO_PORT)(GPIO_PORT_E | PIN)
#define GPIO_PG0                    GPIO_PG(GPIO_PIN_0)
#define GPIO_PG1                    GPIO_PG(GPIO_PIN_1)
#define GPIO_PG2                    GPIO_PG(GPIO_PIN_2)
#define GPIO_PG3                    GPIO_PG(GPIO_PIN_3)
#define GPIO_PG4                    GPIO_PG(GPIO_PIN_4)
#define GPIO_PG5                    GPIO_PG(GPIO_PIN_5)
#define GPIO_PG6                    GPIO_PG(GPIO_PIN_6)
#define GPIO_PG7                    GPIO_PG(GPIO_PIN_7)
#define GPIO_PG8                    GPIO_PG(GPIO_PIN_8)
#define GPIO_PG9                    GPIO_PG(GPIO_PIN_9)
#define GPIO_PG10                   GPIO_PG(GPIO_PIN_10)
#define GPIO_PG11                   GPIO_PG(GPIO_PIN_11)
#define GPIO_PG12                   GPIO_PG(GPIO_PIN_12)
#define GPIO_PG13                   GPIO_PG(GPIO_PIN_13)
#define GPIO_PG14                   GPIO_PG(GPIO_PIN_14)
#define GPIO_PG15                   GPIO_PG(GPIO_PIN_15)

#define GPIO_PH(PIN)                (GPIO_PORT)(GPIO_PORT_E | PIN)
#define GPIO_PH0                    GPIO_PH(GPIO_PIN_0)
#define GPIO_PH1                    GPIO_PH(GPIO_PIN_1)
#define GPIO_PH2                    GPIO_PH(GPIO_PIN_2)
#define GPIO_PH3                    GPIO_PH(GPIO_PIN_3)
#define GPIO_PH4                    GPIO_PH(GPIO_PIN_4)
#define GPIO_PH5                    GPIO_PH(GPIO_PIN_5)
#define GPIO_PH6                    GPIO_PH(GPIO_PIN_6)
#define GPIO_PH7                    GPIO_PH(GPIO_PIN_7)
#define GPIO_PH8                    GPIO_PH(GPIO_PIN_8)
#define GPIO_PH9                    GPIO_PH(GPIO_PIN_9)
#define GPIO_PH10                   GPIO_PH(GPIO_PIN_10)
#define GPIO_PH11                   GPIO_PH(GPIO_PIN_11)
#define GPIO_PH12                   GPIO_PH(GPIO_PIN_12)
#define GPIO_PH13                   GPIO_PH(GPIO_PIN_13)
#define GPIO_PH14                   GPIO_PH(GPIO_PIN_14)
#define GPIO_PH15                   GPIO_PH(GPIO_PIN_15)

#define GPIO_PI(PIN)                (GPIO_PORT)(GPIO_PORT_I | PIN)
#define GPIO_PI0                    GPIO_PI(GPIO_PIN_0)
#define GPIO_PI1                    GPIO_PI(GPIO_PIN_1)
#define GPIO_PI2                    GPIO_PI(GPIO_PIN_2)
#define GPIO_PI3                    GPIO_PI(GPIO_PIN_3)
#define GPIO_PI4                    GPIO_PI(GPIO_PIN_4)
#define GPIO_PI5                    GPIO_PI(GPIO_PIN_5)
#define GPIO_PI6                    GPIO_PI(GPIO_PIN_6)
#define GPIO_PI7                    GPIO_PI(GPIO_PIN_7)
#define GPIO_PI8                    GPIO_PI(GPIO_PIN_8)
#define GPIO_PI9                    GPIO_PI(GPIO_PIN_9)
#define GPIO_PI10                   GPIO_PI(GPIO_PIN_10)
#define GPIO_PI11                   GPIO_PI(GPIO_PIN_11)
#define GPIO_PI12                   GPIO_PI(GPIO_PIN_12)
#define GPIO_PI13                   GPIO_PI(GPIO_PIN_13)
#define GPIO_PI14                   GPIO_PI(GPIO_PIN_14)
#define GPIO_PI15                   GPIO_PI(GPIO_PIN_15)

#define GPIO_PJ(PIN)                (GPIO_PORT)(GPIO_PORT_J | PIN)
#define GPIO_PJ0                    GPIO_PJ(GPIO_PIN_0)
#define GPIO_PJ1                    GPIO_PJ(GPIO_PIN_1)
#define GPIO_PJ2                    GPIO_PJ(GPIO_PIN_2)
#define GPIO_PJ3                    GPIO_PJ(GPIO_PIN_3)
#define GPIO_PJ4                    GPIO_PJ(GPIO_PIN_4)
#define GPIO_PJ5                    GPIO_PJ(GPIO_PIN_5)
#define GPIO_PJ6                    GPIO_PJ(GPIO_PIN_6)
#define GPIO_PJ7                    GPIO_PJ(GPIO_PIN_7)
#define GPIO_PJ8                    GPIO_PJ(GPIO_PIN_8)
#define GPIO_PJ9                    GPIO_PJ(GPIO_PIN_9)
#define GPIO_PJ10                   GPIO_PJ(GPIO_PIN_10)
#define GPIO_PJ11                   GPIO_PJ(GPIO_PIN_11)
#define GPIO_PJ12                   GPIO_PJ(GPIO_PIN_12)
#define GPIO_PJ13                   GPIO_PJ(GPIO_PIN_13)
#define GPIO_PJ14                   GPIO_PJ(GPIO_PIN_14)
#define GPIO_PJ15                   GPIO_PJ(GPIO_PIN_15)

#define GPIO_PK(PIN)                (GPIO_PORT)(GPIO_PORT_K | PIN)
#define GPIO_PK0                    GPIO_PK(GPIO_PIN_0)
#define GPIO_PK1                    GPIO_PK(GPIO_PIN_1)
#define GPIO_PK2                    GPIO_PK(GPIO_PIN_2)
#define GPIO_PK3                    GPIO_PK(GPIO_PIN_3)
#define GPIO_PK4                    GPIO_PK(GPIO_PIN_4)
#define GPIO_PK5                    GPIO_PK(GPIO_PIN_5)
#define GPIO_PK6                    GPIO_PK(GPIO_PIN_6)
#define GPIO_PK7                    GPIO_PK(GPIO_PIN_7)
#define GPIO_PK8                    GPIO_PK(GPIO_PIN_8)
#define GPIO_PK9                    GPIO_PK(GPIO_PIN_9)
#define GPIO_PK10                   GPIO_PK(GPIO_PIN_10)
#define GPIO_PK11                   GPIO_PK(GPIO_PIN_11)
#define GPIO_PK12                   GPIO_PK(GPIO_PIN_12)
#define GPIO_PK13                   GPIO_PK(GPIO_PIN_13)
#define GPIO_PK14                   GPIO_PK(GPIO_PIN_14)
#define GPIO_PK15                   GPIO_PK(GPIO_PIN_15)

#endif 
/*******************************************************************************
**                                END OF FILE                                 **
*******************************************************************************/
